export const FETCH_POPULAR_ITEMS = "FETCH_POPULAR_ITEMS";
export const FETCH_POPULAR_ITEMS_START = "FETCH_POPULAR_ITEMS_START";
export const FETCH_POPULAR_ITEMS_SUCCESS = "FETCH_POPULAR_ITEMS_SUCCESS";
export const FETCH_POPULAR_ITEMS_FAIL = "FETCH_POPULAR_ITEMS_FAIL";
export const SET_UP_POPULAR_ITEMS = "SET_UP_POPULAR_ITEMS";

export const GET_ERRORS = "GET_ERRORS";
export const CLEAR_ERRORS = "CLEAR_ERRORS";

export const USER_AUTH_ERROR = "USER_AUTH_ERROR";
export const USER_LOADING = "USER_LOADING";
export const USER_LOADED = "USER_LOADED";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAIL = "USER_LOGIN_FAIL";
export const USER_LOGOUT_SUCCESS = "USER_LOGOUT_SUCCESS";
export const USER_REGISTER_FAIL = "USER_REGISTER_FAIL";
export const USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS";

export const FETCHING_USER_SETS_START = "FETCHING_USER_SETS_START";
export const FETCHING_USER_SETS_SUCCESS = "FETCHING_USER_SETS_SUCCESS";
export const FETCHING_USER_SETS_FAIL = "FETCHING_USER_SETS_FAIL";
export const CREATING_USER_SET_START = "CREATING_USER_SET_START";
export const CREATING_USER_SET_SUCCESS = "CREATING_USER_SET_SUCCESS";
export const CREATING_USER_SET_FAIL = "CREATING_USER_SET_FAIL";

export const FETCHING_ACTIVE_SET_START = "FETCHING_ACTIVE_SET_START";
export const FETCHING_ACTIVE_SET_SUCCESS = "FETCHING_ACTIVE_SET_SUCCESS";
export const FETCHING_ACTIVE_SET_FAIL = "FETCHING_ACTIVE_SET_FAIL";

