export const FETCH_POPULAR_ITEMS = "FETCH_POPULAR_ITEMS";
export const FETCH_POPULAR_ITEMS_START = "FETCH_POPULAR_ITEMS_START";
export const FETCH_POPULAR_ITEMS_SUCCESS = "FETCH_POPULAR_ITEMS_SUCCESS";
export const FETCH_POPULAR_ITEMS_FAIL = "FETCH_POPULAR_ITEMS_FAIL";
export const SET_UP_POPULAR_ITEMS = "SET_UP_POPULAR_ITEMS";